
package com.opentext.ecm.services.authws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AuthenticationService", targetNamespace = "urn:authws.services.ecm.opentext.com", wsdlLocation = "http://wnsdwsap060.nanshan.com.tw:8080/otdsws/services/Authentication?wsdl")
public class AuthenticationService
    extends Service
{

    private final static URL AUTHENTICATIONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.opentext.ecm.services.authws.AuthenticationService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.opentext.ecm.services.authws.AuthenticationService.class.getResource(".");
            url = new URL(baseUrl, "http://wnsdwsap060.nanshan.com.tw:8080/otdsws/services/Authentication?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://wnsdwsap060.nanshan.com.tw:8080/otdsws/services/Authentication?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        AUTHENTICATIONSERVICE_WSDL_LOCATION = url;
    }

    public AuthenticationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthenticationService() {
        super(AUTHENTICATIONSERVICE_WSDL_LOCATION, new QName("urn:authws.services.ecm.opentext.com", "AuthenticationService"));
    }

    /**
     * 
     * @return
     *     returns Authentication
     */
    @WebEndpoint(name = "AuthenticationPort")
    public Authentication getAuthenticationPort() {
        return super.getPort(new QName("urn:authws.services.ecm.opentext.com", "AuthenticationPort"), Authentication.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Authentication
     */
    @WebEndpoint(name = "AuthenticationPort")
    public Authentication getAuthenticationPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:authws.services.ecm.opentext.com", "AuthenticationPort"), Authentication.class, features);
    }

}
