
package com.opentext.livelink.service.docman;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DocumentManagement", targetNamespace = "urn:DocMan.service.livelink.opentext.com", wsdlLocation = "http://wnsdwsap060.nanshan.com.tw:8080/cws/services/DocumentManagement?wsdl")
public class DocumentManagement_Service
    extends Service
{

    private final static URL DOCUMENTMANAGEMENT_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.opentext.livelink.service.docman.DocumentManagement_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.opentext.livelink.service.docman.DocumentManagement_Service.class.getResource(".");
            url = new URL(baseUrl, "http://wnsdwsap060.nanshan.com.tw:8080/cws/services/DocumentManagement?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://wnsdwsap060.nanshan.com.tw:8080/cws/services/DocumentManagement?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DOCUMENTMANAGEMENT_WSDL_LOCATION = url;
    }

    public DocumentManagement_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocumentManagement_Service() {
        super(DOCUMENTMANAGEMENT_WSDL_LOCATION, new QName("urn:DocMan.service.livelink.opentext.com", "DocumentManagement"));
    }

    /**
     * 
     * @return
     *     returns DocumentManagement
     */
    @WebEndpoint(name = "BasicHttpBinding_DocumentManagement")
    public DocumentManagement getBasicHttpBindingDocumentManagement() {
        return super.getPort(new QName("urn:DocMan.service.livelink.opentext.com", "BasicHttpBinding_DocumentManagement"), DocumentManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentManagement
     */
    @WebEndpoint(name = "BasicHttpBinding_DocumentManagement")
    public DocumentManagement getBasicHttpBindingDocumentManagement(WebServiceFeature... features) {
        return super.getPort(new QName("urn:DocMan.service.livelink.opentext.com", "BasicHttpBinding_DocumentManagement"), DocumentManagement.class, features);
    }

}
