
package com.opentext.livelink.service.recman;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RecordsManagement", targetNamespace = "urn:RecMan.service.livelink.opentext.com", wsdlLocation = "http://wnsdwsap060.nanshan.com.tw:8080/cs-services-recordsmanagement/services/RecordsManagement?wsdl")
public class RecordsManagement_Service
    extends Service
{

    private final static URL RECORDSMANAGEMENT_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.opentext.livelink.service.recman.RecordsManagement_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.opentext.livelink.service.recman.RecordsManagement_Service.class.getResource(".");
            url = new URL(baseUrl, "http://wnsdwsap060.nanshan.com.tw:8080/cs-services-recordsmanagement/services/RecordsManagement?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://wnsdwsap060.nanshan.com.tw:8080/cs-services-recordsmanagement/services/RecordsManagement?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        RECORDSMANAGEMENT_WSDL_LOCATION = url;
    }

    public RecordsManagement_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecordsManagement_Service() {
        super(RECORDSMANAGEMENT_WSDL_LOCATION, new QName("urn:RecMan.service.livelink.opentext.com", "RecordsManagement"));
    }

    /**
     * 
     * @return
     *     returns RecordsManagement
     */
    @WebEndpoint(name = "BasicHttpBinding_RecordsManagement")
    public RecordsManagement getBasicHttpBindingRecordsManagement() {
        return super.getPort(new QName("urn:RecMan.service.livelink.opentext.com", "BasicHttpBinding_RecordsManagement"), RecordsManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecordsManagement
     */
    @WebEndpoint(name = "BasicHttpBinding_RecordsManagement")
    public RecordsManagement getBasicHttpBindingRecordsManagement(WebServiceFeature... features) {
        return super.getPort(new QName("urn:RecMan.service.livelink.opentext.com", "BasicHttpBinding_RecordsManagement"), RecordsManagement.class, features);
    }

}
